(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const h=document.querySelector(".home-img");let u=0,m=0,l=0,a=0;document.addEventListener("mousemove",o=>{u=(o.clientX/window.innerWidth-.5)*30,m=(o.clientY/window.innerHeight-.5)*30});function f(){l+=(u-l)*.1,a+=(m-a)*.1,h.style.transform=`translate(${l}px, ${a}px)`,requestAnimationFrame(f)}f();const i=document.getElementById("contactForm");if(i){const o=i.querySelector(".btn-text"),s=i.querySelector(".btn-loader"),t=i.querySelector(".form-message");i.addEventListener("submit",n=>{n.preventDefault(),o.classList.add("hidden"),s.classList.remove("hidden"),t.classList.add("hidden"),setTimeout(()=>{s.classList.add("hidden"),o.classList.remove("hidden"),t.textContent="Заявка успішно відправлена 🚀",t.classList.remove("hidden"),t.classList.add("success"),i.reset()},2e3)})}const c=document.querySelector(".contact-form.purple");if(c){const o=c.querySelector(".btn-text"),s=c.querySelector(".btn-loader"),t=c.querySelector(".form-message");c.addEventListener("submit",n=>{n.preventDefault(),o.classList.add("hidden"),s.classList.remove("hidden"),t.classList.add("hidden"),setTimeout(()=>{s.classList.add("hidden"),o.classList.remove("hidden"),t.textContent="Заявка відправлена 🚀",t.classList.remove("hidden"),t.classList.add("success"),c.reset()},2e3)})}document.querySelectorAll(".faq-acc-el-trigger").forEach(o=>{o.addEventListener("click",()=>{const s=o.closest(".faq-acc-el"),t=s.querySelector(".faq-acc-el-descr-frame"),n=o.querySelector("svg"),e=s.classList.contains("open"),r=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 12H12H18" stroke="#1D1D1D" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M12.0078 6.00488L12.0078 12.0049L12.0078 18.0049" stroke="#1D1D1D" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 12H12H18" stroke="#1D1D1D" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;e?(s.classList.remove("open"),t.style.maxHeight="0",n.outerHTML=r):(s.classList.add("open"),t.style.maxHeight=t.scrollHeight+"px",n.outerHTML=d)})});
//# sourceMappingURL=index.js.map
